name: news_app_using_newsapi_key
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.9
  firebase_core: ^3.14.0
  firebase_storage: ^12.4.7
  firebase_auth: ^5.6.0
  http: ^1.4.0
  json_annotation: ^4.9.0
  url_launcher: ^6.3.1
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.2.1
  provider: ^6.1.5
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  assets: 
   - 'assets/login_page.jpg'
   - 'assets/high-angle-geometrical-figures-with-copy-space.jpg'
   - 'assets/original-0c6f9674172354fc7fb7ff1915cd2afc.gif'
   - 'assets/Business.jpg'
   - 'assets/Entertainment.jpeg'
   - 'assets/General.jpeg'
   - 'assets/Health.jpeg'
   - 'assets/Sports.jpeg'
