// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDJ7ogzPs5BsfRfl3VUzzQyYiZ7pz6eEA',
    appId: '1:910861388870:android:a4b69536f2b6e252ed8e47',
    messagingSenderId: '910861388870',
    projectId: 'user-registration-95c25',
    storageBucket: 'user-registration-95c25.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2_cRPyAhi46liTv7nlTaz96jS0g7vuls',
    appId: '1:910861388870:web:ca495a8f59b1d879ed8e47',
    messagingSenderId: '910861388870',
    projectId: 'user-registration-95c25',
    authDomain: 'user-registration-95c25.firebaseapp.com',
    storageBucket: 'user-registration-95c25.firebasestorage.app',
    measurementId: 'G-8VNZRXMN08',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPreKxFPEKULoawvh4Zi8kIb476UIUyDA',
    appId: '1:910861388870:ios:8097c6f968359defed8e47',
    messagingSenderId: '910861388870',
    projectId: 'user-registration-95c25',
    storageBucket: 'user-registration-95c25.firebasestorage.app',
    iosBundleId: 'com.example.newsAppUsingNewsapiKey',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPreKxFPEKULoawvh4Zi8kIb476UIUyDA',
    appId: '1:910861388870:ios:8097c6f968359defed8e47',
    messagingSenderId: '910861388870',
    projectId: 'user-registration-95c25',
    storageBucket: 'user-registration-95c25.firebasestorage.app',
    iosBundleId: 'com.example.newsAppUsingNewsapiKey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2_cRPyAhi46liTv7nlTaz96jS0g7vuls',
    appId: '1:910861388870:web:652e5ed43e57fa38ed8e47',
    messagingSenderId: '910861388870',
    projectId: 'user-registration-95c25',
    authDomain: 'user-registration-95c25.firebaseapp.com',
    storageBucket: 'user-registration-95c25.firebasestorage.app',
    measurementId: 'G-B00HYS7J4F',
  );

}